
project_id = "wgzzegyxorlustvfjueb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev", "https://lovableproject.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
secure_password_change_enabled = true
enable_manual_linking = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54325
file_size_limit = "50MiB"

[edge-runtime]
enabled = true
port = 54326

[analytics]
enabled = false
port = 54327

[functions.openai-gpt-chat]
verify_jwt = false

[functions.embed-question]
verify_jwt = false

[functions.embed-doc-chunks]
verify_jwt = false
