// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgzzegyxorlustvfjueb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnenplZ3l4b3JsdXN0dmZqdWViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDY1MTUsImV4cCI6MjA2NDcyMjUxNX0.whCobDW-MZku9S72M8fZDi0rZeu00cYSJttntmUH0vM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);